services:
  ntp:
    build: ./ntp
    container_name: ntp_server
    networks:
      lab_net:
        ipv4_address: 172.28.0.4
    ports:
      - "20123:123/udp"
    cap_add:
      - SYS_TIME
    restart: unless-stopped
  dns_server:
    build: ./dns
    container_name: dns_server
    image: my-bind9-image
    ports:
      - "20053:53/udp"
      - "20053:53/tcp"
    networks:
      lab_net:
        ipv4_address: 172.28.0.5
    restart: always
  vpn_server:
    build: ./vpn
    container_name: vpn_server
    ports:
      - "21194:1194/udp"
    networks:
      lab_net:
        ipv4_address: 172.28.0.2
    cap_add:
      - NET_ADMIN
    volumes:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
  postgres_radius:
    build: ./radius/db
    container_name: postgres_radius
    environment:
      POSTGRES_DB: radius
      POSTGRES_USER: radius
      POSTGRES_PASSWORD: radpass
    networks:
      lab_net:
        ipv4_address: 172.28.0.3
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  radius_server:
    build: ./radius/raddb
    container_name: radius_server
    ports:
      - "21812:1812/udp"
      - "21813:1813/udp"
    networks:
      lab_net:
        ipv4_address: 172.28.0.6
    depends_on:
      - postgres_radius
    environment:
      SQL_HOST: postgres_radius
      SQL_USER: radius
      SQL_PASS: radpass
    restart: unless-stopped

networks:
  lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24

volumes:
  postgres_data:
