services:
  ntp:
    build: ./ntp
    container_name: ntp_server
    networks:
      lab_net:
        ipv4_address: 172.28.0.4
    ports:
      - "20123:123/udp"
    cap_add:
      - SYS_TIME
    restart: unless-stopped
  dns_server:
    build: ./dns
    container_name: dns_server
    image: my-bind9-image
    ports:
      - "20053:53/udp"
      - "20053:53/tcp"
    networks:
      sae_network:
        ipv4_address: 172.28.0.5
    restart: always

networks:
  lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24

        
